### ISSUE TITLE
 Uncaught RangeError: Offset is outside the bounds of the DataView

### ISSUE THREAD

**Issue by JakeChampion** [43081j/id3#23]
This error came from the line `var bomInt = this.getUint16(offset);`. Not sure what else I should put into this ticket to help debug. If you can think of anything I could do, just say :-)

**Comment by Amalthean** [comment]
Yep, same thing happened to me but on this line:
```javascript
// line 625 dist/id3.js
if(dv.getUint8(i) === 0x00) {
  variableStart = i + 1;
  break;
}
```

**Comment by Alafazam** [comment]
I am facing the same Error.
It Happens when I use a higher bit rate (320kbps) file.

**Comment by gorjuspixels** [comment]
This is a duplicate. Please refer to https://github.com/43081j/id3/issues/6

**Comment by JakeChampion** [comment]
Thanks for the link, closing this as duplicate.
