### ISSUE TITLE
Genre Failure

### ISSUE THREAD

**Issue by EverydayDiesel** [43081j/id3#26]
Hello, 
First off I want to complement you on a very good library however there is one rather serious error.

In a ID3V2 tag you can have any genre, not just the ones you listed in the array.  If you read a file that has a genre that is not in your array then the app crashses.

/id3js/dist/id3.js:231
var bomInt = this.getUint16(offset);

Is there any plans to extract the actual id3v2 genre string instead of converting it to a number?

**Comment by gorjuspixels** [comment]
This is a duplicate. Please refer to https://github.com/43081j/id3/issues/6
