### ISSUE TITLE
Support promises instead of callbacks

### ISSUE THREAD

**Issue by MichaelMarner** [43081j/id3#39]
Interested in making this library support promises to allow for using `async`/`await`. Wanted to start a  discussion over whether it's worth the effort support both callbacks and Promises, or whether to do a semver major version change and support only promises going forward?

Thought?

**Comment by 43081j** [comment]
This could be part of the push to typescript (2.x), pretty much replacing what we can with async/await as no need for backwards compatibility in the major bump.

**Comment by ashinzekene** [comment]
I was about making a PR to support promises, with backward compatibility

**Comment by 43081j** [comment]
Essentially if #38 can get finished or we make a push for v2 (typescript), this would become a non-issue as it would be part of the transition (in fact to async/await).

I don't think its worth a separate PR as the current codebase needs a major refactor anyway.
